In [ ]:
#Bài 1
def scale(a, v):
   return [a*vi for vi in v]

def sumvector(v, w):
  return [vi+wi for (vi, wi) in zip(v, w)]

def dotvector(v, w):
  return sum([vi*wi for(vi, wi) in zip(v, w)])

def lenvector(v):
  return dotvector(v, v)

v = [3, 5, 7]
w = [2, 4, 6]

print(scale(10, v))
print(sumvector(v, w))
print(dotvector(v, w))
print(lenvector(w))

[30, 50, 70]
[5, 9, 13]
68
56


In [ ]:
#Bài 2
import numpy as np
scores = np.array([-1, 1, 2, -3, 5, -4])
print(np.select([scores >=0, scores <0],['so duong', 'so am'], default='unknown'))
scores = np.array([-1, 1, 2, 0, -3, 5, 0, -4])
print(np.select([scores >0, scores ==0, scores < 0],['so duong', 'so 0', 'so am'], default='unknown'))

['so am' 'so duong' 'so duong' 'so am' 'so duong' 'so am']
['so am' 'so duong' 'so duong' 'so 0' 'so am' 'so duong' 'so 0' 'so am']


In [3]:
#Bài 3.1
import numpy as np
from scipy import linalg, sparse
D = np.asmatrix([ [3,4], [5,6] ])
print (D)
C = np.asmatrix(np.random.random((5,7)))
print (C)
A = np.asmatrix(np.random.random((2,2)))
print (A)
b = np.array([(1+5j, 2j, 3j),(4, 5, 6)])
B = np.asmatrix(b)
print (b)
print (B)
A.T
A.I
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
v_diag = np.diag(M)
print (v_diag)
M_diag = np.diag(v_diag)
print (M_diag)
I2 = np.identity(2)
import sympy as sp
x = sp.Symbol('x')
y = sp.Symbol('y')
z = sp.Symbol('z')
sp.solve([x*x+2-6, y-1-6,x+z-1, 2*x*x-8, z*z+4-5,y-z-8], [x, y, z])
x = [1, 2, 3]
y = [1, 2, 3]
print(all([x[i]==y[i] for i in range(len(x))]))
#True
y = [1, 2, 4]
print(all([x[i]==y[i] for i in range(len(x))]))
#False
import numpy as np
print(np.array_equal([1, 2], [1, 2]))
#True
print(np.array_equal(np.array([1,2]), np.array([1,2])))
#True

[[3 4]
 [5 6]]
[[0.30937259 0.5536348  0.09238955 0.91774817 0.70459885 0.9619671
  0.04463026]
 [0.86760891 0.82178317 0.29832877 0.34516152 0.40189901 0.09369308
  0.51409962]
 [0.44578797 0.81510463 0.77378845 0.18112825 0.26888385 0.13574057
  0.180574  ]
 [0.05213775 0.89329955 0.09573859 0.70513039 0.32131979 0.3255578
  0.55087265]
 [0.52096552 0.10222612 0.09150993 0.44915963 0.89802412 0.97117637
  0.94888493]]
[[0.9852002  0.39221868]
 [0.93411055 0.2525526 ]]
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]
[-1 -2 -2]
[[-1  0  0]
 [ 0 -2  0]
 [ 0  0 -2]]
True
False
True
True


In [5]:
#Bài 3.2
import numpy as np
A = np.reshape(np.arange(36.0), (6,6))
print (A)
I6 = np.identity(6)
print (I6)
A.size
np.matrix.diagonal(A)
A = A + I6
print (A)
vecB = np.array([1., 2., 3., 4., 5., 6.])
C = A.dot(vecB)
print (C)
D = np.array([[1., 2., 3., 4., 5., 6.], [1., 0., 1., 0., 1., 0.]])
print (D)
E = A.dot(D.T)
F = np.array([[1., 1.], [2., 0.], [3., 1.], [4., 0], [5., 1], [6., 0.]])
G = A.dot(F)
print (F)
print (G)
np.linalg.inv(A)
np.linalg.inv(np.linalg.inv(A))

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[ 1.  1.  2.  3.  4.  5.]
 [ 6.  8.  8.  9. 10. 11.]
 [12. 13. 15. 15. 16. 17.]
 [18. 19. 20. 22. 22. 23.]
 [24. 25. 26. 27. 29. 29.]
 [30. 31. 32. 33. 34. 36.]]
[ 71. 198. 325. 452. 579. 706.]
[[1. 2. 3. 4. 5. 6.]
 [1. 0. 1. 0. 1. 0.]]
[[1. 1.]
 [2. 0.]
 [3. 1.]
 [4. 0.]
 [5. 1.]
 [6. 0.]]
[[ 71.   7.]
 [198.  24.]
 [325.  43.]
 [452.  60.]
 [579.  79.]
 [706.  96.]]


array([[ 1.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  8.,  8.,  9., 10., 11.],
       [12., 13., 15., 15., 16., 17.],
       [18., 19., 20., 22., 22., 23.],
       [24., 25., 26., 27., 29., 29.],
       [30., 31., 32., 33., 34., 36.]])

In [6]:
#Bài 4
import numpy as np
A = np.array( [ [1,1], [1,0] ] )
b = np.array([1, 0])
n = 10
for i in range(n):
  b = A.dot(b)
  print(b)

[1 1]
[2 1]
[3 2]
[5 3]
[8 5]
[13  8]
[21 13]
[34 21]
[55 34]
[89 55]


In [8]:
#Bài 5.2
import sympy as sp
from sympy import Symbol
x1 = Symbol('x1')
x2 = Symbol('x2')
x3 = Symbol('x3')
x4 = Symbol('x4')
from sympy import solve
pt1 = x4+610-450-x1
pt2 = x1+400-x2-640
pt3 = x2+600-x3
pt4 = x3-x4-520
nghiem = sp.solve((pt1, pt2, pt3, pt4))
nghiem
import numpy as np
A = np.matrix([[-1,0,0,1],[1,-1,0,0],[0,1,-1,0],[0,0,1,-1]])
A_nghichdao = np.linalg.inv(A)

{x1: x4 + 160, x2: x4 - 80, x3: x4 + 520}

In [9]:
#Bài tập
#Câu 1
import numpy as np
# Vấn đề 1: Tìm giao điểm của hai đường thẳng
A1 = np.array([[1, -3],
               [2, 3]])
b1 = np.array([2, 6])
x1 = np.linalg.solve(A1, b1)
print("Vấn đề 1: Giao điểm hai đường thẳng là:", x1)

# Vấn đề 2: Tìm giao điểm của 3 mặt phẳng
A2 = np.array([[1, -2, 1],
               [3, -1, -1],
               [1, 1, 1]])
b2 = np.array([3, -3, 6])
x2 = np.linalg.solve(A2, b2)
print("Vấn đề 2: Giao điểm ba mặt phẳng là:", x2)

# Vấn đề 3: Tìm hệ số a, b, c sao cho p(x) thỏa 3 điểm
A3 = np.array([[1, 1, 1],
               [4, 2, 1],
               [9, 3, 1]])
b3 = np.array([4, 3, 4])
x3 = np.linalg.solve(A3, b3)
print("Vấn đề 3: Hệ số của đa thức bậc 2 là a, b, c:", x3)

# Vấn đề 4: Tìm hệ số khi phân tích tích phân
A4 = np.array([[1, 1, 1],
               [-3, 2, -1],
               [2, 2, 0]])
b4 = np.array([0, 3, 0])
x4 = np.linalg.solve(A4, b4)
print("Vấn đề 4: Các hệ số a, b, c là:", x4)

Vấn đề 1: Giao điểm hai đường thẳng là: [2.66666667 0.22222222]
Vấn đề 2: Giao điểm ba mặt phẳng là: [0.75 1.   4.25]
Vấn đề 3: Hệ số của đa thức bậc 2 là a, b, c: [ 1. -4.  7.]
Vấn đề 4: Các hệ số a, b, c là: [-0.6  0.6  0. ]


In [10]:
#Câu 2
from sympy import symbols, Eq, solve, Matrix
x, y, z, a, b, c = symbols('x y z a b c')
# Vấn đề 1
eqs1 = [Eq(x - 3*y, 2),
        Eq(2*x + y, 6)]
sol1 = solve(eqs1, (x, y))
print("Vấn đề 1 sympy:", sol1)

# Vấn đề 2
eqs2 = [Eq(x - 2*y + z, 3),
        Eq(3*x - y - z, -3),
        Eq(x + y + z, 6)]
sol2 = solve(eqs2, (x, y, z))
print("Vấn đề 2 sympy:", sol2)

# Vấn đề 3
eqs3 = [Eq(a + b + c, 4),
        Eq(4*a + 2*b + c, 3),
        Eq(9*a + 3*b + c, 4)]
sol3 = solve(eqs3, (a, b, c))
print("Vấn đề 3 sympy:", sol3)

# Vấn đề 4
eqs4 = [Eq(a + b + c, 0),
        Eq(-3*a + 2*b - c, 3),
        Eq(2*a + 2*b, 0)]
sol4 = solve(eqs4, (a, b, c))
print("Vấn đề 4 sympy:", sol4)

Vấn đề 1 sympy: {x: 20/7, y: 2/7}
Vấn đề 2 sympy: {x: 3/4, y: 1, z: 17/4}
Vấn đề 3 sympy: {a: 1, b: -4, c: 7}
Vấn đề 4 sympy: {a: -3/5, b: 3/5, c: 0}


In [11]:
#Câu 3
import numpy as np
def matrix_power(F, n):
    result = np.identity(len(F), dtype=int)
    while n > 0:
        if n % 2 == 1:
            result = np.dot(result, F)
        F = np.dot(F, F)
        n //= 2
    return result
# Ma trận Fibonacci
F = np.array([[1, 1], [1, 0]], dtype=int)
k = 10
Fk = matrix_power(F, k)
print(f"F^{k} =\n", Fk)
print("Fib(k+1):", Fk[0][0])
print("Fib(k):", Fk[1][0])

F^10 =
 [[89 55]
 [55 34]]
Fib(k+1): 89
Fib(k): 55
